# Generated by Django 5.0.1 on 2024-01-11 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "CategoryName",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("AgeMin", models.IntegerField()),
                ("AgeMax", models.IntegerField()),
                ("Time", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BookName", models.CharField(max_length=45)),
                ("Is_barrowed", models.BooleanField()),
                (
                    "CategoryName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App1.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BirthDate", models.DateField()),
                ("PhoneNumber", models.CharField(max_length=10)),
                ("Address", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Barrowed_book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DateBarrowed", models.DateField()),
                ("ReturnDate", models.DateField()),
                (
                    "BookId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App1.book"
                    ),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App1.person"
                    ),
                ),
            ],
        ),
    ]
